services:
  elasticsearch:
      image: elasticsearch:8.11.1
      container_name: elasticsearch
      ports: 
        - 9200:9200
      volumes:
        - data01:/usr/share/elasticsearch/data
      environment: 
        - discovery.type=single-node
        - xpack.security.enabled=false        
      networks:
        - elastic
  kibana-latest:
      image: kibana:8.11.1
      container_name: kibana
      depends_on:
          - elasticsearch
      ports:
      - "5601:5601"
      networks:
        - elastic
      environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
networks:
  elastic:
    driver: bridge
volumes:
  data01:
    driver: local
      
